### ISSUE TITLE
CI considers linter warnings as failures, should be warnings

### ISSUE THREAD

**Issue by longsleep** [libregraph/idm#21]

**Comment by rhafer** [comment]
@longsleep Do you mean that all of the linter issues should be treated as warning? (i.e. not make the action fail)
 Or to do want to tone down some specific linters?

Do you have a specific example of a linter issue that shouldn't cause the CI to fail?

**Comment by longsleep** [comment]
> all of the linter issues should be treated as warning

Yes. Imo we should not too script if the code otherwise builds.

> Or to do want to tone down some specific linters

Probably some configs could be adapted, but thats can be tweaked later.

**Comment by rhafer** [comment]
hm, that didn't completely fix it. The annotation show up as warnings now. But the ci is still failing :man_shrugging:
