### ISSUE TITLE
Can't build on alpine linux

### ISSUE THREAD

**Issue by rhafer** [libregraph/idm#49]
The used go-crypt module contains glibc specific code. Alpine linux is using musl instead of glibc.

```
owncloud/idm # make
running gofmt ...
retrieving dependencies ...
# github.com/Azure/go-ntlmssp v0.0.0-20211209120228-48547f28849e
...
building cmd/idmd ...
CGO_ENABLED=1 go build \
        -mod=vendor \
        -trimpath \
        -tags release \
        -buildmode=exe \
        -ldflags '-s -w -buildid=reproducible/0.3.0-41-gb89b052 -X github.com/libregraph/idm/version.Version=0.3.0-41-gb89b052 -X github.com/libregraph/idm/version.BuildDate=2022-02-17T17:28:53Z -extldflags -static' \
        -o bin/idmd ./cmd/idmd
# github.com/amoghe/go-crypt
vendor/github.com/amoghe/go-crypt/version.go:6:10: fatal error: gnu/libc-version.h: No such file or directory
    6 | #include <gnu/libc-version.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:47: cmd/idmd] Error 2
```

**Comment by longsleep** [comment]
Yes this is like it is - only glibc on some platforms provides good enough crypt. Ideally there would be a runtime check at startup if the loaded crypt actually supports the required modern alg - and if not crypt should refuse to do things

**Comment by rhafer** [comment]
> Yes this is like it is - only glibc on some platforms provides good enough crypt.

musl also has support for some hashing algorithms that AFAIK are still considered ok to use (e.g. bcrypt)

> Ideally there would be a runtime check at startup if the loaded crypt actually supports the required modern alg - and if not crypt should refuse to do things
>
> Reasoning is that it must be avoided to generated crappy password hashes.

I guess this is meant as a generic (not specific to idm) comment. And I mostly agree with that. Though I guess for idm this is not exactly relevant. Currently we don't support to generate new password hashes other than argon2id. The crypt support is mainly just there to be able to import and verify password from already existing sources. (At least that's what I interpret into the current code)
