### ISSUE TITLE
idm overwrites standard logger

### ISSUE THREAD

**Issue by rhafer** [libregraph/idm#54]
To be able to properly log messages of the `ldap` module idm is "redirecting" the standard logger to logrus:

https://github.com/libregraph/idm/blob/master/server/server.go#L131

We are currently trying to embed the idm service  into ocis and this is creating a bit of on issue with any other go module that might be using the standard logger. (All messages will get the `scope=ldap` thing added, even if they come from completely unrelated code). 

Maybe we should make that log redirection optional somehow.

**Comment by longsleep** [comment]
I guess idm should not do any kind of implicit logging initialization when not run through its own main package.

**Comment by rhafer** [comment]
Turns out that, since v3.4.3 go-ldap/ldap allows to set configure a custom logger. Setting that should also solve this issue.

@longsleep BTW would you mind if we moved pkg/ldapserver/ to use logrus instead of the go standard log module. So that at least inside idm itself logging is somewhat aligned?

**Comment by longsleep** [comment]
> BTW would you mind if we moved pkg/ldapserver/ to use logrus instead of the go standard log module. So that at least inside idm itself logging is somewhat aligned?

I prefer https://github.com/go-logr/logr for libraries as that does retain flexibility for library consumers.
